version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post123
      - POSTGRES_DB=product_management
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_HOST=redis
    depends_on:
      - database
      - rabbitmq
      - redis

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
      POSTGRES_DB: product_management
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
